[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8002
#workers = 24
keep_alive = 5
log = "normal"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8003
workers = 24
keep_alive = 5
log = "critical"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[global.tls]
certs = "D://myrust/phoenix_chain/data/crt/pub.pem"
key= "D://myrust/phoenix_chain/data/crt/key.pem"
